name: Sync to Hugging Face

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Unshallow the repository

      - name: Install Git LFS
        run: |
          sudo apt-get install git-lfs
          git lfs install

      - name: Configure Git
        run: |
          git config --global credential.helper store
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          echo "machine huggingface.co login github-actions password ${{ secrets.HF_TOKEN }}" > ~/.netrc

      - name: Debug Environment
        run: |
          echo "HF_TOKEN=${{ secrets.HF_TOKEN }}"
          git remote -v

      - name: Push changes to Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git remote add hf https://huggingface.co/spaces/JayM7/annotation
          git push hf main --force
