name: Groq Auto-Fix
on:
  workflow_run:
    workflows: [ "CI Tests", "Build and Deploy" ]
    types: [ completed ]

jobs:
  auto-fix:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Run MCP GitHub Fixes with Groq
        run: |
          npx -y @modelcontextprotocol/server-github \
          --llm groq \
          --api-key groq=${{ secrets.GROQ_API_KEY }}
