name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgl1

      - name: Upgrade Build Tools
        run: |
          python -m pip install --upgrade pip setuptools wheel --no-cache-dir

      - name: Install Compatible Numpy Version
        run: |
          pip install numpy==1.21.6 --force-reinstall --no-cache-dir

      - name: Debug Installed Libraries (Before Spacy)
        run: |
          python -c "import numpy; print(f'Numpy: {numpy.__version__}')"
          
      - name: Create Clean temp-requirements.txt    
        run: |
          grep -vE 'detectron2|spacy|mmcv' requirements.txt > temp-requirements.txt
          cat temp-requirements.txt  # Debugging output

      - name: Install PyTorch First
        run: |
          pip install torch==1.12.0+cpu torchvision==0.13.0+cpu torchaudio==0.12.0+cpu --extra-index-url https://download.pytorch.org/whl/cpu   

      - name: Ensure Clean MMCV Install
        run: |
          pip uninstall -y mmcv mmcv-full
          pip install mmcv-full==1.7.1 -f https://download.openmmlab.com/mmcv/dist/cpu/torch1.12/index.html

      - name: Debug MMCV Installation
        run: |
          pip list | grep mmcv

      - name: Install Other Dependencies (Without Detectron2 and Spacy)
        run: |
          pip install --no-cache-dir -r temp-requirements.txt

      - name: Install Build Dependencies
        run: |
          pip install --upgrade setuptools wheel Cython
          
      - name: Install Required Cython Dependencies
        run: |
          pip install --no-cache-dir \
            cymem==2.0.6 \
            preshed==3.0.8 \
            murmurhash==1.0.9 \
            blis==0.7.9 \
            thinc==8.1.9 \
            numpy==1.21.6 \
            setuptools>=59.6.0 \
            Cython==0.29.37
                
      - name: Install SpaCy Without Version Pinning
        run: |
          pip install --no-deps --no-cache-dir --use-pep517 --no-build-isolation "spacy>=3.8,<3.9"
        continue-on-error: true

      - name: Debug Installed Libraries
        run: |
          pip list
          python -c "import numpy; print(f'Numpy: {numpy.__version__}')"
          
      - name: Verify Installation
        run: |
          python -c "import spacy; print(spacy.__version__)"
        
      - name: Debug Installed Libraries (After Spacy)
        run: |
          python -c "import numpy, spacy; print(f'Numpy: {numpy.__version__}, Spacy: {spacy.__version__}')"

      - name: Install Detectron2 Separately
        run: |
          pip install --no-cache-dir git+https://github.com/facebookresearch/detectron2.git@d1e04565d3bec8719335b88be9e9b961bf3ec464#egg=detectron2

      - name: Run Tests
        run: |
          pytest
